Testing tag validation

diff --git a/.github/workflows/deploy-qa.yml b/.github/workflows/deploy-qa.yml
--- a/.github/workflows/deploy-qa.yml
+++ b/.github/workflows/deploy-qa.yml
@@ -3,7 +3,7 @@ name: Deploy to QA Environment
 on:
   push:
     tags:
-    - '**.**.**'
+    - '[0-9]+[0-9]+\.[0-9]+[0-9]+\.[0-9]+[0-9]+'
     
 jobs:
   deploy-app-qa:
@@ -14,14 +14,14 @@ jobs:
       - uses: actions/checkout@v2
         with:
           ref: 'main'
-      - name: Check tag format
-        run: |
-          if [[ ${{ github.event.ref }} =~ ^refs/tags/[0-9]+[0-9]+\.[0-9]+[0-9]+\.[0-9]+[0-9]+$ ]]; then
-            echo ::set-output name=match::true
-          else
-            echo 'Invalid Tag format'
-            exit 1
-          fi
+      # - name: Check tag format
+      #   run: |
+      #     if [[ ${{ github.event.ref }} =~ ^refs/tags/[0-9]+[0-9]+\.[0-9]+[0-9]+\.[0-9]+[0-9]+$ ]]; then
+      #       echo ::set-output name=match::true
+      #     else
+      #       echo 'Invalid Tag format'
+      #       exit 1
+      #     fi
       - name: Get current SHA from Main branch
         id: main
         run: |
