Adding format validation for tags

diff --git a/.github/workflows/deploy-qa.yml b/.github/workflows/deploy-qa.yml
--- a/.github/workflows/deploy-qa.yml
+++ b/.github/workflows/deploy-qa.yml
@@ -14,10 +14,18 @@ jobs:
       - uses: actions/checkout@v2
         with:
           ref: 'main'
+      - name: Check tag format
+        run: |
+          if [[ ${{ github.event.ref }} =~ ^refs/tags/[0-9]+[0-9]+\.[0-9]+[0-9]+\.[0-9]+[0-9]+$ ]]; then
+            echo ::set-output name=match::true
+          else
+            echo 'Invalid Tag format'
+            exit 1
+          fi
       - name: Get current SHA from Main branch
         id: main
         run: |
-          echo "::set-output name=COMMIT_SHA::$(git log -n 1  --format='%H' main)"
+          echo "::set-output name=COMMIT_SHA::$(git log -n 1 --format='%H' main)"
       - name: Deploy app
         uses: ./.github/actions/deploy-backstage-app
         with:
